# playbooks/recovery_strategy_B.yml
- name: Recovery Strategy B – Selective Restore
  hosts: bastion
  gather_facts: no
  tasks:

    - name: Mark recovery B start
      shell: |
        echo "recovery_start{strategy=\"B\"} $(date +%s)" | \
        curl --data-binary @- {{ pushgateway_url }}/metrics/job/recovery_events/scenario/{{ scenario_id }}

    - name: Get DB pod
      shell: kubectl get pod -l {{ db_pod_label }} -n {{ namespace }} -o jsonpath='{.items[0].metadata.name}'
      register: db_pod

    - name: Restore critical tables only
      shell: |
        kubectl exec {{ db_pod.stdout }} -n {{ namespace }} -- \
        psql -U {{ db_user }} {{ db_name }} < {{ backup_dir }}/selective/critical_tables.sql

    - name: Run integrity checks
      shell: |
        kubectl exec {{ db_pod.stdout }} -n {{ namespace }} -- \
        psql -U {{ db_user }} {{ db_name }} -c "SELECT COUNT(*) FROM clinical_notes;"

    - name: Mark recovery B end
      shell: |
        echo "recovery_end{strategy=\"B\"} $(date +%s)" | \
        curl --data-binary @- {{ pushgateway_url }}/metrics/job/recovery_events/scenario/{{ scenario_id }}
