kind: IOChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: postgres-pvc-io-failure
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: postgres
  mode: all
  action: fault
  errno: 5
  percent: 100
  volumePath: /var/lib/postgresql/data
  duration: 2m
